FROM node:16.15.1-alpine
WORKDIR /app
COPY package*.json ./
ENV CLIEND_ID $CLIEND_ID
ENV DB_HOST $DB_HOST
ENV DB_USER $DB_USER
ENV DB_PWD $DB_PWD
ENV DB_NAME $DB_NAME
ENV SECRET_KEY $SECRET_KEY
ENV PORT $PORT
ENV SERVER $SERVER
ENV CLIENT_ID $CLIENT_ID
ENV CLIENT_SECRET $CLIENT_SECRET
ENV ACCESS_TOKEN $ACCESS_TOKEN
ENV REFRESH_TOKEN $REFRESH_TOKEN
ENV FRONT_SERVER_LOGIN_URL $FRONT_SERVER_LOGIN_URL
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_REGION $AWS_REGION
ENV AWS_BUCKET_NAME $AWS_BUCKET_NAME
ENV MY_SSH $MY_SSH
ENV SIGNED_URL_PRIVATE_KEY $SIGNED_URL_PRIVATE_KEY
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
EXPOSE 8080